[general]
import = [
    "~/.config/alacritty/themes/themes/tokyo_night_enhanced.toml"
]

[font]
normal = { family = "CaskaydiaMono Nerd Font", style = "Regular" }
size = 10

[window]
decorations = "None"
