code --install-extension asvetliakov.vscode-neovim
code --install-extension ban.spellright
code --install-extension editorconfig.editorconfig
code --install-extension enkia.tokyo-night
code --install-extension github.vscode-pull-request-github
code --install-extension hbenl.vscode-test-explorer
code --install-extension helgardrichard.helium-icon-theme
code --install-extension jtlowe.vscode-icon-theme
code --install-extension mechatroner.rainbow-csv
code --install-extension mesonbuild.mesonbuild
code --install-extension ms-dotnettools.csdevkit
code --install-extension ms-dotnettools.csharp
code --install-extension ms-dotnettools.vscode-dotnet-runtime
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.cpptools-extension-pack
code --install-extension ms-vscode.cpptools-themes
code --install-extension ms-vscode.test-adapter-converter
code --install-extension redhat.vscode-xml
code --install-extension redhat.vscode-yaml
code --install-extension rust-lang.rust-analyzer
code --install-extension swellaby.vscode-rust-test-adapter
code --install-extension tamasfe.even-better-toml
code --install-extension twxs.cmake
code --install-extension yummygum.city-lights-icon-vsc
